export const PERSON_ADD = "PERSON_ADD";
export const PERSON_REMOVE = "PERSON_REMOVE";
export const PERSON_UPDATE = "PERSON_UPDATE";
/*export const PERSON_GET_ALL = "PERSON_GET_ALL";*/
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";
export const FETCH_POSTS_START = "FETCH_POSTS_START";